FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu

RUN apt-get update && \
    apt-get install -y build-essential cmake gcc g++ gdb \
    openjdk-17-jdk \
    python3 python3-pip \
    dotnet-sdk-8.0 \
    sqlite3 mysql-client postgresql-client
